### ISSUE TITLE
Enhancement checklist

### ISSUE THREAD

**Issue by Sh3b0** [Sh3B0/PongMe#1]
- [ ] Start ball movement from a random direction
- [ ] Show ping and player status (disconnected, ready, paused, won, lost).
- [ ] Add replay button and functionality
- [ ] Add settings menu and logic
- [ ] Research how to make the gameplay smoother
